[package]
name = "main"
version = "0.1.0"
edition = "2021"

[dependencies]
fastnoise-lite = "1.1.1"
image = "0.25.5"
minifb = "0.27.0"
nalgebra-glm = "0.18.0"
rand = "0.8.5"
rodio = "0.20.1"
rusttype = "0.9.3"
tobj = "4.0.2"
